# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ced7c9f7f42a33c9bddd25d3310aec48d1c3bde761fa059407657cf89db70dc2bb0971712e10921d9faa905a9597c45d753822c3afceca08a04f3e7f60e7dca

test:
  secret_key_base: 316d4f79902997290ca52e604564505dcbaf6f0d34bc5a680c95862b2095d6395e6a2e5405a1dbb012faf66c92577a735d9d53b8790a0e884430fe55c0b76b6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
